raw <- read.table("household_power_consumption.txt",header = TRUE, sep = ";", na="?", stringsAsFactors = FALSE)
raw$Time <- strptime(paste(raw$Date,raw$Time), "%d/%m/%Y %H:%M:%S")
raw$Date <- as.Date(raw$Date, "%d/%m/%Y")
dates <- as.Date(c("2007-02-01", "2007-02-02"), "%Y-%m-%d")
data <- subset(raw, Date %in% dates)
png(filename = "plot3.png")
plot(data$Time, data$Sub_metering_1, type="l", col="black", xlab="", ylab="Energy sub metering")
lines(data$Time, data$Sub_metering_2, col="red")
lines(data$Time, data$Sub_metering_3, col="blue")
dev.off()
